package com.anvorgueso.dexium.core.util

/**
 * Type names per language, generated from PokeAPI's `/type/{id}` `names` arrays.
 *
 * Baked in rather than fetched: it is 18 rows that never change, and fetching would mean 18
 * requests every time the language changes. Keys are the canonical capitalized English names
 * that [TypeChart] and the entities use.
 */
object LocalizedTypeNames {

    private val byLanguage: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "Normal" to "Normal",
            "Fire" to "Fire",
            "Water" to "Water",
            "Electric" to "Electric",
            "Grass" to "Grass",
            "Ice" to "Ice",
            "Fighting" to "Fighting",
            "Poison" to "Poison",
            "Ground" to "Ground",
            "Flying" to "Flying",
            "Psychic" to "Psychic",
            "Bug" to "Bug",
            "Rock" to "Rock",
            "Ghost" to "Ghost",
            "Dragon" to "Dragon",
            "Dark" to "Dark",
            "Steel" to "Steel",
            "Fairy" to "Fairy"
        ),
        "es" to mapOf(
            "Normal" to "Normal",
            "Fire" to "Fuego",
            "Water" to "Agua",
            "Electric" to "Eléctrico",
            "Grass" to "Planta",
            "Ice" to "Hielo",
            "Fighting" to "Lucha",
            "Poison" to "Veneno",
            "Ground" to "Tierra",
            "Flying" to "Volador",
            "Psychic" to "Psíquico",
            "Bug" to "Bicho",
            "Rock" to "Roca",
            "Ghost" to "Fantasma",
            "Dragon" to "Dragón",
            "Dark" to "Siniestro",
            "Steel" to "Acero",
            "Fairy" to "Hada"
        ),
        "es-419" to mapOf(
            "Normal" to "Normal",
            "Fire" to "Fuego",
            "Water" to "Agua",
            "Electric" to "Eléctrico",
            "Grass" to "Planta",
            "Ice" to "Hielo",
            "Fighting" to "Pelea",
            "Poison" to "Veneno",
            "Ground" to "Tierra",
            "Flying" to "Volador",
            "Psychic" to "Psíquico",
            "Bug" to "Insecto",
            "Rock" to "Roca",
            "Ghost" to "Fantasma",
            "Dragon" to "Dragón",
            "Dark" to "Siniestro",
            "Steel" to "Acero",
            "Fairy" to "Hada"
        ),
        "fr" to mapOf(
            "Normal" to "Normal",
            "Fire" to "Feu",
            "Water" to "Eau",
            "Electric" to "Électrik",
            "Grass" to "Plante",
            "Ice" to "Glace",
            "Fighting" to "Combat",
            "Poison" to "Poison",
            "Ground" to "Sol",
            "Flying" to "Vol",
            "Psychic" to "Psy",
            "Bug" to "Insecte",
            "Rock" to "Roche",
            "Ghost" to "Spectre",
            "Dragon" to "Dragon",
            "Dark" to "Ténèbres",
            "Steel" to "Acier",
            "Fairy" to "Fée"
        ),
        "de" to mapOf(
            "Normal" to "Normal",
            "Fire" to "Feuer",
            "Water" to "Wasser",
            "Electric" to "Elektro",
            "Grass" to "Pflanze",
            "Ice" to "Eis",
            "Fighting" to "Kampf",
            "Poison" to "Gift",
            "Ground" to "Boden",
            "Flying" to "Flug",
            "Psychic" to "Psycho",
            "Bug" to "Käfer",
            "Rock" to "Gestein",
            "Ghost" to "Geist",
            "Dragon" to "Drache",
            "Dark" to "Unlicht",
            "Steel" to "Stahl",
            "Fairy" to "Fee"
        ),
        "it" to mapOf(
            "Normal" to "Normale",
            "Fire" to "Fuoco",
            "Water" to "Acqua",
            "Electric" to "Elettro",
            "Grass" to "Erba",
            "Ice" to "Ghiaccio",
            "Fighting" to "Lotta",
            "Poison" to "Veleno",
            "Ground" to "Terra",
            "Flying" to "Volante",
            "Psychic" to "Psico",
            "Bug" to "Coleottero",
            "Rock" to "Roccia",
            "Ghost" to "Spettro",
            "Dragon" to "Drago",
            "Dark" to "Buio",
            "Steel" to "Acciaio",
            "Fairy" to "Folletto"
        ),
        "ja" to mapOf(
            "Normal" to "ノーマル",
            "Fire" to "ほのお",
            "Water" to "みず",
            "Electric" to "でんき",
            "Grass" to "くさ",
            "Ice" to "こおり",
            "Fighting" to "かくとう",
            "Poison" to "どく",
            "Ground" to "じめん",
            "Flying" to "ひこう",
            "Psychic" to "エスパー",
            "Bug" to "むし",
            "Rock" to "いわ",
            "Ghost" to "ゴースト",
            "Dragon" to "ドラゴン",
            "Dark" to "あく",
            "Steel" to "はがね",
            "Fairy" to "フェアリー"
        ),
        "ja-hrkt" to mapOf(
            "Normal" to "ノーマル",
            "Fire" to "ほのお",
            "Water" to "みず",
            "Electric" to "でんき",
            "Grass" to "くさ",
            "Ice" to "こおり",
            "Fighting" to "かくとう",
            "Poison" to "どく",
            "Ground" to "じめん",
            "Flying" to "ひこう",
            "Psychic" to "エスパー",
            "Bug" to "むし",
            "Rock" to "いわ",
            "Ghost" to "ゴースト",
            "Dragon" to "ドラゴン",
            "Dark" to "あく",
            "Steel" to "はがね",
            "Fairy" to "フェアリー"
        ),
        "ko" to mapOf(
            "Normal" to "노말",
            "Fire" to "불꽃",
            "Water" to "물",
            "Electric" to "전기",
            "Grass" to "풀",
            "Ice" to "얼음",
            "Fighting" to "격투",
            "Poison" to "독",
            "Ground" to "땅",
            "Flying" to "비행",
            "Psychic" to "에스퍼",
            "Bug" to "벌레",
            "Rock" to "바위",
            "Ghost" to "고스트",
            "Dragon" to "드래곤",
            "Dark" to "악",
            "Steel" to "강철",
            "Fairy" to "페어리"
        ),
        "zh-hans" to mapOf(
            "Normal" to "一般",
            "Fire" to "火",
            "Water" to "水",
            "Electric" to "电",
            "Grass" to "草",
            "Ice" to "冰",
            "Fighting" to "格斗",
            "Poison" to "毒",
            "Ground" to "地面",
            "Flying" to "飞行",
            "Psychic" to "超能力",
            "Bug" to "虫",
            "Rock" to "岩石",
            "Ghost" to "幽灵",
            "Dragon" to "龙",
            "Dark" to "恶",
            "Steel" to "钢",
            "Fairy" to "妖精"
        ),
        "zh-hant" to mapOf(
            "Normal" to "一般",
            "Fire" to "火",
            "Water" to "水",
            "Electric" to "電",
            "Grass" to "草",
            "Ice" to "冰",
            "Fighting" to "格鬥",
            "Poison" to "毒",
            "Ground" to "地面",
            "Flying" to "飛行",
            "Psychic" to "超能力",
            "Bug" to "蟲",
            "Rock" to "岩石",
            "Ghost" to "幽靈",
            "Dragon" to "龍",
            "Dark" to "惡",
            "Steel" to "鋼",
            "Fairy" to "妖精"
        )
    )

    /** Falls back to the English name, which is also the key, so nothing renders blank. */
    fun of(canonicalType: String, language: String): String =
        byLanguage[language]?.get(canonicalType)
            ?: byLanguage["en"]?.get(canonicalType)
            ?: canonicalType

    /** Every localized spelling of every type, for resolving a stored name back to its key. */
    fun allSpellings(): List<Pair<String, String>> =
        byLanguage.values.flatMap { table -> table.map { (key, name) -> name to key } }
}
